language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode7.3

    - os: osx
      osx_image: xcode8

    - os: osx
      osx_image: xcode9

cache:
  directories:
    - $HOME/Library/Caches/pip
    - $HOME/Library/Caches/Homebrew

script:
  - ./install_all
